### ISSUE TITLE
ttkDesigner: Adding a layout to main window, and then trying to delete it provoke a crash

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#138]
If you add a Layout Widget, then try to delete it (not main window) it crahses with:

```
Traceback (most recent call last):
  File "/home/larry/IdeaProjects/support/system/bin/ttkDesigner", line 8, in <module>
    sys.exit(main())
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/ttkDesigner/app/main.py", line 47, in main
    root.mainloop()
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 163, in mainloop
    self._mainLoop()
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 173, in _mainLoop
    self._input.start()
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 77, in start
    self.key_process(stdinRead)
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 161, in key_process
    self.inputEvent.emit(kevt, mevt)
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 140, in emit
    slot(*args[sl], **kwargs)
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 179, in _processInput
    self._key_event(kevt)
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 240, in _key_event
    keyHandled = focusWidget.keyEvent(kevt)
  File "/home/larry/IdeaProjects/support/system/lib/python3.10/site-packages/ttkDesigner/app/superobj/supercontrol.py", line 83, in keyEvent
    not self._wid.isRootWidget() ):
AttributeError: 'SuperLayoutGrid' object has no attribute 'isRootWidget'. Did you mean: 'parentWidget'?
```

I went into `supercontrol.py`  and modified `keyEvent`  method into this:
```
    def keyEvent(self, evt):
        try:
            if evt.type == ttk.TTkK.SpecialKey:
                if ( evt.key in (ttk.TTkK.Key_Delete, ttk.TTkK.Key_Backspace) and
                     not self._wid.isRootWidget() ):
                    self._wid.parentWidget().removeSuperWidget(self._wid)
                    self._wid.close()
                    self.close()
                    self._wid._designer.weModified.emit()
                    return True
                bkPos = self.pos()
                x,y = 0,0
                if evt.key == ttk.TTkK.Key_Up:    y=-1
                elif evt.key == ttk.TTkK.Key_Down:  y=1
                elif evt.key == ttk.TTkK.Key_Left:  x=-1
                elif evt.key == ttk.TTkK.Key_Right: x=1
                if any((x,y)):
                    self.move(bkPos[0]+x, bkPos[1]+y)
                    self._alignWidToPos(bkPos)
        except BaseException as be:
            if evt.type == ttk.TTkK.SpecialKey:
                if ( evt.key in (ttk.TTkK.Key_Delete, ttk.TTkK.Key_Backspace) and
                     self._wid.parentWidget() ):
                    self._wid.parentWidget().removeSuperWidget(self._wid)
                    self._wid.close()
                    self.close()
                    self._wid._designer.weModified.emit()
                    return True
                bkPos = self.pos()
                x,y = 0,0
                if evt.key == ttk.TTkK.Key_Up:    y=-1
                elif evt.key == ttk.TTkK.Key_Down:  y=1
                elif evt.key == ttk.TTkK.Key_Left:  x=-1
                elif evt.key == ttk.TTkK.Key_Right: x=1
                if any((x,y)):
                    self.move(bkPos[0]+x, bkPos[1]+y)
                    self._alignWidToPos(bkPos)
```
and it stopped crashing when you delete a layout. -- this seems to happen only with layouts.

this "patch"  keep it working, but of course I'm not sure it can break something else -- and probably is not the best way to do it (ie catching the exception)

**Comment by ceccopierangiolieugenio** [comment]
my fault
isRootWidget is not implemented in the SuperLayout,
in the future you will be able to initialize a new layout
