### ISSUE TITLE
ttkDesigner exception when clicking any layout in the editor

### ISSUE THREAD

**Issue by russkel** [ceccopierangiolieugenio/pyTermTk#175]
If I start `ttkDesigner` and then drag in a layout, and then click that layout I get this exception:

```
Traceback (most recent call last):
  File "/home/russ/.local/bin/ttkDesigner", line 8, in <module>
    sys.exit(main())
  File "/home/russ/.local/lib/python3.10/site-packages/ttkDesigner/app/main.py", line 47, in main
    root.mainloop()
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 169, in mainloop
    self._mainLoop()
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 179, in _mainLoop
    self._input.start()
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 77, in start
    self.key_process(stdinRead)
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 161, in key_process
    self.inputEvent.emit(kevt, mevt)
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 140, in emit
    slot(*args[sl], **kwargs)
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 187, in _processInput
    self._mouse_event(mevt)
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 227, in _mouse_event
    if not self.mouseEvent(mevt):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 419, in mouseEvent
    if  TTkWidget._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 394, in _mouseEventLayoutHandle
    if TTkWidget._mouseEventLayoutHandle(levt, item):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 390, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 419, in mouseEvent
    if  TTkWidget._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 394, in _mouseEventLayoutHandle
    if TTkWidget._mouseEventLayoutHandle(levt, item):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 390, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 419, in mouseEvent
    if  TTkWidget._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 394, in _mouseEventLayoutHandle
    if TTkWidget._mouseEventLayoutHandle(levt, item):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 394, in _mouseEventLayoutHandle
    if TTkWidget._mouseEventLayoutHandle(levt, item):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 390, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 419, in mouseEvent
    if  TTkWidget._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 394, in _mouseEventLayoutHandle
    if TTkWidget._mouseEventLayoutHandle(levt, item):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 390, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/widget.py", line 489, in mouseEvent
    if evt.tap == 1 and self.mousePressEvent(evt):
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidget.py", line 231, in mousePressEvent
    self.itemClicked.emit(item, col)
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 140, in emit
    slot(*args[sl], **kwargs)
  File "/home/russ/.local/lib/python3.10/site-packages/ttkDesigner/app/treeinspector.py", line 55, in _itemSelected
    self._designer.thingSelected.emit(tomw, wi.tomSuperWidget())
  File "/home/russ/.local/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 140, in emit
    slot(*args[sl], **kwargs)
  File "/home/russ/.local/lib/python3.10/site-packages/ttkDesigner/app/designer.py", line 131, in <lambda>
    self.thingSelected.connect(lambda _,s : s.pushSuperControlWidget() if s.hasControlWidget() else None)
AttributeError: 'SuperLayoutVBox' object has no attribute 'hasControlWidget'
```

```
↳ python3 --version
Python 3.10.12

↳ pip3 list | grep -i tk
catkin-pkg                           1.0.0
catkin-pkg-modules                   1.0.0
pyTermTk                             0.31.0a8
ttkDesigner                          0.30.0a128
```

**Comment by ceccopierangiolieugenio** [comment]
try the latest version **0.34.0a** this issue should be fixed

**Comment by russkel** [comment]
They are indeed. Lovely, thanks.
