### ISSUE TITLE
TTkList Widget: Removing elements from it provoke an error when want to select different item

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#180]
HI,
This time I'm trying to implement a window to move things from one list to another.

Long Story short:
My program actually reads a JSON formatted file, detects what are relevant fields, and then pops up a windows to select what are fields I want to see on a single line, it looks like this:

<img width="1332" alt="Screenshot 2023-10-06 at 12 30 28" src="https://github.com/ceccopierangiolieugenio/pyTermTk/assets/56597585/91f1b702-e6ef-4afe-9c46-ad82020c334b">

But when I move (or essentially delete an item from one list and add it to second one) all seems to be ok, but when I try to select a second field it crash with following error:

```
Traceback (most recent call last):
  File "/Users/larry.castro/IdeaProjects/logtracer/showlog", line 1006, in <module>
    interactive_work()
  File "/Users/larry.castro/IdeaProjects/logtracer/showlog", line 920, in interactive_work
    root.mainloop()
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/ttk.py", line 176, in mainloop
    self._mainLoop()
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/ttk.py", line 186, in _mainLoop
    self._input.start()
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 81, in start
    self.key_process(stdinRead)
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 174, in key_process
    self.inputEvent.emit(kevt, mevt)
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/signal.py", line 143, in emit
    slot(*args[sl], **kwargs)
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/ttk.py", line 200, in _processInput
    self._mouse_event(mevt)
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkCore/ttk.py", line 240, in _mouse_event
    if not self.mouseEvent(mevt):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 246, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 221, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 217, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 246, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 221, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 217, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 246, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 221, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 217, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 246, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 221, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 217, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 246, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 221, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/container.py", line 217, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/widget.py", line 352, in mouseEvent
    w.setFocus()
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/widget.py", line 510, in setFocus
    self.focusInEvent()
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/listwidget.py", line 302, in focusInEvent
    self._moveToHighlighted()
  File "/Users/larry.castro/IdeaProjects/logtracer/system/lib/python3.9/site-packages/TermTk/TTkWidgets/listwidget.py", line 250, in _moveToHighlighted
    index = self._items.index(self._highlighted)
ValueError: <TermTk.TTkWidgets.listwidget.TTkAbstractListItem object at 0x1038ab7c0> is not in list
```
Correct me if I'm wrong but what I think issue is here, the "Highlight" method probably is trying to "unselect" previous item (which no longer exist because I deleted it) and then crash because can't find it... I'm right? 

I've tried to search for a method to "clear all selections" from list after I delete any item within, but I think you do not have any method to do that... if you do please let me know.

this is last way I've tried it, but always got same error:

```
            original_list = list(fieldsList.items())
            items = list(fieldsList.items())
            if fieldsList.selectedLabels():
                # Add items to second list
                for s in fieldsList.selectedItems():
                    fieldlist_toshow.addItem(str(s.text()))
                    # Remove items from temporary list
                    items.remove(s)

                # Delete all items from fieldList
                for each_item in original_list:
                    fieldsList.removeItem(each_item)

                # add just items that were not removed
                for each_item in items:
                    fieldsList.addItem(str(each_item.text()))
```

Initially I've attempted to delete actual item directly at the widget, but when I got error I thought that probably cause was I was interacting directly with widget, so I tried this approach to do all in a different list, then update list with all items again except the ones I deleted... but it doesn't work either...

Also I think I can do this with Drag and Drop events, using lists?

**Comment by castben** [comment]
Ok it seems that always that I have an issue and posted, I found later a solution... :D  

Any way solution, or workaround was to use a method (which I saw you suggested to someone else):

fieldsList.setCurrentRow(0) 

so it will force selected item to be always  first one that appears...

But I'm sensing another issue here, what will happen when all items are deleted? I can't assign any item as all will be deleted...

**Comment by ceccopierangiolieugenio** [comment]
I need to investigate this issue, the list should be more stable and not cause this kind of crashes.
btw, I think a drag and drop could be easily implemented in the list itself,
I think I have to check how to include this feature

**Comment by ceccopierangiolieugenio** [comment]
I delivered the fix in **0.34.0a7**

You can check this example:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/0e5162fe0b07611a087e1f8757d50c03f29f4997/tests/test.ui.014.list.03.py

I need to work on the drag and drop feature of the list

**Comment by ceccopierangiolieugenio** [comment]
WIP:

https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/f258d836-3117-4ae7-bec0-ccc6e4bb47a6

**Comment by ceccopierangiolieugenio** [comment]
hi @castben 
I removed the default drag and drop in the liist to avoid unexpected dnd
you need to enable it explicitly as shown in the demo file:

```python
    listWidgetSingle = ttk.TTkList(parent=win1, maxWidth=40, minWidth=10, dragDropMode=ttk.TTkK.AllowDragDrop)
    listWidgetMulti = ttk.TTkList(parent=win2, maxWidth=40, minWidth=10, dragDropMode=ttk.TTkK.AllowDragDrop, selectionMode=ttk.TTkK.MultiSelection)
    listWidgetDrag = ttk.TTkList(parent=win4, maxWidth=40, minWidth=10, dragDropMode=ttk.TTkK.AllowDrag)
    listWidgetDrop = ttk.TTkList(parent=win5, maxWidth=40, minWidth=10, dragDropMode=ttk.TTkK.AllowDrop)
```

**Comment by castben** [comment]
Hi,
Got it thank you for let me know. I will take care of this
