### ISSUE TITLE
Demo 'textedit.py' does not run

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#25]
I get the following error when I try to run `/demo/showcase/textedit.py`:
```
$ python textedit.py
Traceback (most recent call last):
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 69, in <module>
    main()
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 65, in main
    demoTextEdit(rootTree)
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 48, in demoTextEdit
    te.setReadOnly(False)
AttributeError: 'TTkTextEdit' object has no attribute 'setReadOnly'
```

I tried to fix the code by changing line 48 to `te.isReadOnly = False`, but then I got another error:
```
$ python textedit.py
Traceback (most recent call last):
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 69, in <module>
    main()
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 65, in main
    demoTextEdit(rootTree)
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 49, in demoTextEdit
    te.setText(ttk.TTkString('\n').join([ getSentence(5,25,i) for i in range(50)]))
TypeError: TTkString.__init__() takes 1 positional argument but 2 were given
```

So it seems that the code might be broken in more than just one place...

**Comment by ceccopierangiolieugenio** [comment]
Hi @jeffwright13 
I think that the textedit is trying to use the pyTermTk library installed using pip (v0.7.x)
The new textedit was introduced in the version v0.8.0 not yet pushed to pip.
try to remove the pyTermTk installed using pip and run the demo from the root folder of the repo.
```demo/showcase/textedit.py```

**Comment by jeffwright13** [comment]
Thanks for the reply - yeah, I removed the pip-installed version and was able to run from the root directory, as you had said.
