### ISSUE TITLE
Rendering ANSI-encoded text corrupts terminal output

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#26]
Hello,

I'm working on a pyTermTk app that takes the terminal output from a Pytest run (which is ANSI-encoded text), and renders it inside a `TTkTextEdit` widget. It seems that every line that has ANSI codes in it results in some corruption of the rendered text on the screen. 

Here is a stripped down source file to demonstrate what I mean. BTW I am running on a MacBook Pro, running in iTerm2.

```
import TermTk as ttk
from os import get_terminal_size

PYTEST_STATS = 8 * """[31m================================================= [31m[1m7 failed[0m, [32m3 passed[0m, [33m1 skipped[0m, [33m1 xfailed[0m, [33m1 xpassed[0m, [31m[1m2 errors[0m[31m in 0.93s[0m[31m =================================================[0m"""

PYTEST_OUTPUT = 10 * """[1m========================================================================== test session starts ===========================================================================[0m
platform darwin -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/jwr003/coding/pytest-fold/venv/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.2', 'Platform': 'macOS-12.2.1-x86_64-i386-64bit', 'Packages': {'pytest': '6.2.5', 'py': '1.11.0', 'pluggy': '1.0.0'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'Faker': '13.0.0', 'fold': '0.7.4'}, 'JAVA_HOME': '/Users/jwr003/Library/Java/JavaVirtualMachines/corretto-11.0.12/Contents/Home'}
rootdir: /Users/jwr003/coding/pytest-fold, configfile: pytest.ini, testpaths: tests
plugins: html-3.1.1, metadata-1.11.0, Faker-13.0.0, fold-0.7.4
[1mcollecting ... [0m[1m
collected 15 items                                                                                                                                                       [0m

tests/test_pytest_fold.py::test_1_passes_and_has_lots_of_logging_output [32mPASSED[0m[32m                                                                                     [  6%][0m
tests/test_pytest_fold.py::test_2_fails_and_has_lots_of_logging_output [31mFAILED[0m[31m                                                                                      [ 13%][0m
tests/test_pytest_fold.py::test_3_fails [31mFAILED[0m[31m                                                                                                                     [ 20%][0m
tests/test_pytest_fold.py::test_4_passes [32mPASSED[0m[31m                                                                                                                    [ 26%][0m
tests/test_pytest_fold.py::test_5_marked_SKIP [33mSKIPPED[0m (unconditional skip)[31m                                                                                         [ 33%][0m
tests/test_pytest_fold.py::test_6_marked_xfail_but_passes [33mXPASS[0m[31m                                                                                                    [ 40%][0m
tests/test_pytest_fold.py::test_7_marked_xfail_and_fails [33mXFAIL[0m[31m                                                                                                     [ 46%][0m
tests/test_pytest_fold.py::test_8_causes_a_warning [31mFAILED[0m[31m                                                                                                          [ 53%][0m
tests/test_pytest_fold.py::test_8_5_lorem_fails [31mFAILED[0m[31m                                                                                                             [ 60%][0m
tests/test_pytest_fold.py::test_9_fail_capturing [31mFAILED[0m[31m                                                                                                            [ 66%][0m
tests/test_pytest_fold.py::test_10_pass_capturing [31mFAILED[0m[31m                                                                                                           [ 73%][0m
tests/test_pytest_fold.py::test_11_fails_and_has_stdout [31mFAILED[0m[31m                                                                                                     [ 80%][0m
tests/test_pytest_fold.py::test_12_passes_and_has_stdout [32mPASSED[0m[31m                                                                                                    [ 86%][0m
tests/test_pytest_fold.py::test_13_causes_error_pass_stderr_stdout_stdlog [31mERROR[0m[31m                                                                                    [ 93%][0m
tests/test_pytest_fold.py::test_14_causes_error_fail_stderr_stdout_stdlog [31mERROR[0m[31m                                                                                    [100%]\n\n"""


def main():
    root = ttk.TTk()
    term_size = get_terminal_size()

    main_window = ttk.TTkWindow(
        parent=root,
        pos=(0, 0),
        size=(term_size.columns, term_size.lines),
        title=PYTEST_STATS,
        border=True,
    )
    main_layout = ttk.TTkHBoxLayout()
    main_window.setLayout(main_layout)

    tab_widget = ttk.TTkTabWidget(parent=main_window)

    text_edit = ttk.TTkTextEdit(parent=tab_widget)
    text_edit.setText(PYTEST_OUTPUT)
    tab_widget.addTab(text_edit, "Pytest Results")

    root.mainloop()


if __name__ == "__main__":
    main()

```

**Comment by jeffwright13** [comment]
Unfortunately, the ANSI in source file above gets stripped when I post it in the comment, so it doesn't show the problem. 

[This link](https://drive.google.com/file/d/17QbBmBKY7umQIk0rc9BnIbSvS04SIS1N/view?usp=sharing) is a file that has the correctly encoded output, and which will show the problem.

**Comment by jeffwright13** [comment]
Here is a screenshot of the main issue when first rendered:
![image](https://user-images.githubusercontent.com/4308435/159142148-e895fbb7-b0d5-4aa2-a0df-91ca13252cd9.png)

I also noticed that if I scroll up and down using the mouse wheel, parts of the original text output get "stuck in place", while other parts of the text respond to the mouse wheel scrolling. This further corrupts the output:
![image](https://user-images.githubusercontent.com/4308435/159142169-a49352e3-4d00-483b-9243-45901e73fe09.png)

**Comment by ceccopierangiolieugenio** [comment]
The ANSI input is not supported yet (as the support of the tab key),
This is something I was planning to do but never had time to implement it,
I thing It will be the next feature I wil work on.
So far, as long the the only ansii codes used are the colors manipulation (and not the cursor placement or other terminal commands), this may not require too much effort and I should be able to make a drop in the next few days.

**Comment by ceccopierangiolieugenio** [comment]
Added a Basic ANSI support in:
https://github.com/ceccopierangiolieugenio/pyTermTk/commit/a12f3a957cbd22e2381ffc32de2a84e84dbdc7b5

![image](https://user-images.githubusercontent.com/8876552/159173454-fdf17f1e-fd83-4728-b7e2-eefb17ebafc8.png)

Still there may be issues if in the output there are tabs (you can quickly workaround them substituting them with a fixed number of spaces).

**Comment by jeffwright13** [comment]
Thanks, I would like to try this - but how do I install PyTermTk without the pip version being updated? `pip install .` does not work.
```
    ERROR: Command errored out with exit status 1:
     command: /Users/jwr003/coding/pytest-fold/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4m/m1s_1zv505zbznbv3fkbn_cwkkh758/T/pip-req-build-bp9xskh8/setup.py'"'"'; __file__='"'"'/private/var/folders/4m/m1s_1zv505zbznbv3fkbn_cwkkh758/T/pip-req-build-bp9xskh8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4m/m1s_1zv505zbznbv3fkbn_cwkkh758/T/pip-pip-egg-info-x0meplgn
         cwd: /private/var/folders/4m/m1s_1zv505zbznbv3fkbn_cwkkh758/T/pip-req-build-bp9xskh8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4m/m1s_1zv505zbznbv3fkbn_cwkkh758/T/pip-req-build-bp9xskh8/setup.py", line 2, in <module>
        from tmp.TermTk.TTkCore.cfg import TTkCfg
    ModuleNotFoundError: No module named 'tmp'
    ----------------------------------------
    ```

**Comment by jeffwright13** [comment]
I was able to hack up your `setup.py` and get it to install. Looks like your fix above was enough to make the output from Pytest happy - no more corrupted output! Thanks!

**Comment by ceccopierangiolieugenio** [comment]
I just have a symblic link to the **TermTk** in the home folder of any of my projects if I don't want to install it.
i.e.
![image](https://user-images.githubusercontent.com/8876552/159184903-44ac9e3d-79ea-4574-aecd-c66677cf0be2.png)

**Comment by ceccopierangiolieugenio** [comment]
With the latest commit the TextEdit widget should survive also if there are tabs in the input,
I still have not implemented  the selection/edit/cursor position if there re tabs in the line

**Comment by jeffwright13** [comment]
Thanks for the tip on the symbolic link, that works

**Comment by ceccopierangiolieugenio** [comment]
ANSI support in TTkString added in https://github.com/ceccopierangiolieugenio/pyTermTk/commit/a12f3a957cbd22e2381ffc32de2a84e84dbdc7b5
