### ISSUE TITLE
Trying to do sorting (Click on headers) on a tree view crashes

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#270]
Hello hope you are doing well;

I've implemented your `TTkTree`  widget in my project and it works great;

My initial implementation was adding all rows into top level (no childs) but then I realised will be better to group rows into a similar key, this is create a "top" row and then add required childs

Here is code, basically I've a data structure that I convert it into a Dictionary that will hold an array of related items to dictionary key, basically to make later tree over that dictionary.

here is the code:
```python
    tree_view = ttk.TTkTree(parent=load_lab_window)

    headers = {
        'Customer name': 25,
        'Ticket number': 15,
        'Brief description': 25,
        'Created on': 12,
        'Sample used': 28,
        'File name': 100
    }
    # setup headers on treeview
    tree_view.setHeaderLabels(list(headers.keys()))

    # This will hold each brach with its child
    #
    pre_tree = {}

    for each_line in list_plans:
        row = []
        # Add data from list of labs, build each row depending on what are fields I'm asking for
        #
        for each_header in headers:
            row.append(list_plans[each_line][each_header])

        keytree = row[0].strip()

        if keytree not in pre_tree:
            pre_tree[keytree] = []

        pre_tree[keytree].append(row)

    # Create tree
    for each_top in pre_tree:
        # Now Add this row into tree_view
        tree_row = ttk.TTkTreeWidgetItem([each_top,"-","-","-","-"])

        for each_child in pre_tree[each_top]:
            tree_row_child = ttk.TTkFileTreeWidgetItem(each_child)
            tree_row.addChild(tree_row_child)
            tree_row.setExpanded(True)

        tree_view.addTopLevelItem(tree_row)
...

```
And result is this:

![image](https://github.com/user-attachments/assets/8d7661d3-4c43-43f4-87d3-6323731ed7bd)

Which is what I was looking for a better layout for my previous tree that was plain. My problem is when I click on the 'Headers' to order them (any header), it crash with following stacktrace:

```log
Traceback (most recent call last):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/./lab-constructor.py", line 4147, in <module>
    tui_menu()
  File "/home/larry/IdeaProjects/investigations/lab-constructor/./lab-constructor.py", line 3972, in tui_menu
    rootWindow.mainloop()
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 179, in mainloop
    self._mainLoop()
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 189, in _mainLoop
    TTkInput.start()
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input_thread.py", line 102, in start
    TTkInput.inputEvent.emit(kevt, mevt)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 143, in emit
    slot(*args[sl], **kwargs)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 203, in _processInput
    self._mouse_event(mevt)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 243, in _mouse_event
    if not self.mouseEvent(mevt):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 247, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 222, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 218, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 247, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 222, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 218, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 247, in mouseEvent
    if  TTkContainer._mouseEventLayoutHandle(evt, self.rootLayout()):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 222, in _mouseEventLayoutHandle
    if TTkContainer._mouseEventLayoutHandle(levt, item):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 218, in _mouseEventLayoutHandle
    if widget.mouseEvent(wevt):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/container.py", line 317, in mouseEvent
    if evt.tap == 1 and self.mousePressEvent(evt):
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidget.py", line 252, in mousePressEvent
    self.sortItems(i, order)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidget.py", line 170, in sortItems
    self._rootItem.sortChildren(col, order)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidgetitem.py", line 291, in sortChildren
    self._sort(children=True)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidgetitem.py", line 284, in _sort
    c.sortChildren(self._sortColumn, self._sortOrder)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidgetitem.py", line 291, in sortChildren
    self._sort(children=True)
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidgetitem.py", line 276, in _sort
    self._children = sorted(
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/treewidgetitem.py", line 278, in <lambda>
    key = lambda x : x.sortData(self._sortColumn),
  File "/home/larry/IdeaProjects/investigations/lab-constructor/system/lib/python3.10/site-packages/TermTk/TTkWidgets/TTkModelView/filetreewidgetitem.py", line 59, in sortData
    return self._raw[col]
TypeError: 'NoneType' object is not subscriptable

```
I've no idea what could be problem. I was working on PyTermTk version 0.30.x and I upgraded into latest version you have available, but error persist.

It was working before without using child tree feature, when I've intruduced childs on each branch then it crash when I click on any header...

I just tested it again taking all child setup for each 'key' branch and sorting is working:

![image](https://github.com/user-attachments/assets/162dde86-10d2-4cdc-ad4b-5f263f4eed0c)

So definetly is something I'm doing wrong when setting up child hierarchy...

I will appreciate any advice you may have.

Thank you.

**Comment by ceccopierangiolieugenio** [comment]
Yes, I think it is that the main reason.
The raw is a specialised variable used only in the filetree, (I should make "TTkFileTreeWidgetItem" an internal object because it is not supposed to be used elsewhere)
Thanks, I will remove it in the next release

**Comment by castben** [comment]
You see!, only Creator of this fantastic project can spot that so quickly!

I think problem was intelliJSense that "help" you to type stuff, for sure I did not pay attention to actual widget when I hit enter!

Yes that was issue (I was sure it was a stupid thing sorry!) 

I've changed it to proper one and now it is working!

Thank you so much, pleease set this to closed
