### ISSUE TITLE
Demo "demo.py" does not run

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#28]
```
$ python /Users/jwr003/coding/pyTermTk/demo/demo.py
Traceback (most recent call last):
  File "/Users/jwr003/coding/pyTermTk/demo/demo.py", line 246, in <module>
    main()
  File "/Users/jwr003/coding/pyTermTk/demo/demo.py", line 241, in main
    demoShowcase(winTabbed1, border)
  File "/Users/jwr003/coding/pyTermTk/demo/demo.py", line 154, in demoShowcase
    tabWidgets.addTab(demoTextEdit(),    " Text Edit ")
  File "/Users/jwr003/coding/pyTermTk/demo/showcase/textedit.py", line 49, in demoTextEdit
    te.setText(ttk.TTkString('\n').join([ getSentence(5,25,i) for i in range(50)]))
TypeError: TTkString.__init__() takes 1 positional argument but 2 were given
```

**Comment by ceccopierangiolieugenio** [comment]
This could be related to the olf library installed with pip as happened in #25
